baseurl = "https://khanhicetea.com/"
publishdir = "docs"
languageCode = "en-us"
title = "KhanhIceTea B(rain)-log"
canonifyurls = true
googleAnalytics = "UA-50390703-1"
summaryLength = 16
copyright = "KhanhIceTea - All rights reserved"
paginate = 6
paginatePath = "page"
relativeURLs = true
uglyURLs = false


[Params]
    Author = "KhanhIceTea"
    disqusShortname = "khanhicetea"
    GitHubUsername = "khanhicetea"
    LinkedInUrl = "https://vn.linkedin.com/in/khanhicetea"
    SidebarRecentLimit = 5
    SyntaxHighlightTheme = "monokai-sublime.min.css"
    logo = "/images/kit_logo.png"
    description ="Does it matter ? Nope !!"
    mailchimp = "you can provide a mailchimp-link here, see below"
    mailprotect = "you can provide a protector-name here, see below"

[sitemap]
    changefreq = "daily"
    priority = 0.7

[params.author]
    name = "KhanhIceTea"
    thumbnail = "/images/author.jpg"
    description = "Creator of this blog."

[params.social]
    github = "khanhicetea"
    linkedin = "khanhicetea"
    xing = "khanhicetea"
