baseurl = "https://khanhicetea.com"
publishdir = "docs"
languageCode = "en-us"
title = "KhanhIceTea B(rain)-log"
canonifyurls = true
googleAnalytics = "UA-50390703-1"
summaryLength = 16
copyright = "KhanhIceTea - Licensed under CC BY-NC-ND 3.0 | In God We Trust"
paginate = 9
paginatePath = "page"
relativeURLs = true
uglyURLs = false


[Params]
    disqusShortname = "khanhicetea"
    GitHubUsername = "khanhicetea"
    LinkedInUrl = "https://vn.linkedin.com/in/khanhicetea"
    SidebarRecentLimit = 5
    SyntaxHighlightTheme = "monokai-sublime.min.css"
    logo = "/images/kit_logo.png"
    description ="Does it matter ? Nope !!"
    mailchimp = "https://khanhicetea.us13.list-manage.com/subscribe/post?u=2be43c527dca86c033d390369&amp;id=febb4cd208"
    mailprotect = "b_2be43c527dca86c033d390369_febb4cd208"

[sitemap]
    changefreq = "daily"
    priority = 0.7

[Params.author]
  name = "Khanh Nguyen"
  thumbnail = "/images/khanhicetea.jpg"

[Params.social]
    github = "khanhicetea"
    linkedin = "khanhicetea"
    xing = "khanhicetea"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 50
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Github"
    weight = 100
    identifier = "github"
    url = "https://github.com/khanhicetea"
[[menu.main]]
    name = "Today I Learned"
    identifier = "imprint"
    weight = 200
    url = "/til/"
