version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:0.49
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: "git update submodule"
          command: git submodule update --recursive --remote
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo --theme=mediumish-gohugo-theme --buildFuture -d dist
      - add_ssh_keys:
          fingerprint:
            - "8e:0f:7e:b2:16:00:d7:ad:3e:a3:11:b2:85:12:df:a7"
      - run:
          name: "Config Git User Email"
          command: git config --global user.email bot@khanhicetea.com
      - run:
          name: "Config Git User Name"
          command: git config --global user.name KhanhIceTea_Bot
      - run:
          name: "Publish to Github"
          command: .circleci/publish_to_gh
