version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:0.48
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: "git update submodule"
          command: git submodule update --recursive --remote
      - run:
          name: "test"
          command: ls -al themes/mediumish-gohugo-theme
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v --theme=mediumish-gohugo-theme --buildFuture -d dist
      - add_ssh_keys:
          fingerprint:
            - "0c:df:98:33:17:0d:03:8f:78:fb:5e:6d:56:d8:c3:e1"
      - run:
          name: "Config Git User Email"
          command: git config --global user.email bot@khanhicetea.com
      - run:
          name: "Config Git User Name"
          command: git config --global user.name KhanhIceTea_Bot
      - run:
          name: "Publish to Github"
          command: .circleci/publish_to_gh
